package inventorycashiering;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;

public class RegisterPage extends javax.swing.JFrame {

    /**
     * Creates new form RegisterPage
     */
    public RegisterPage() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        passwordfield = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        confirmpassfield = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        registrationRegisterbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        registerResetBtn = new javax.swing.JButton();
        registerBackbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jCheckBoxShowPass = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        rolebox = new javax.swing.JComboBox<>();
        fNamefield = new javax.swing.JTextField();
        lNamefield = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordfield.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        passwordfield.setBorder(null);
        jPanel2.add(passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 260, 38));

        jLabel1.setBackground(new java.awt.Color(51, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Role:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 94, 27));

        confirmpassfield.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        confirmpassfield.setBorder(null);
        jPanel2.add(confirmpassfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 260, 41));

        jLabel9.setBackground(new java.awt.Color(51, 0, 0));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("First Name: ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 110, 27));

        jLabel2.setBackground(new java.awt.Color(51, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Last Name:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 110, 21));

        registrationRegisterbtn.setBackground(new java.awt.Color(0, 153, 255));
        registrationRegisterbtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        registrationRegisterbtn.setForeground(new java.awt.Color(255, 255, 255));
        registrationRegisterbtn.setText("Register");
        registrationRegisterbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        registrationRegisterbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrationRegisterbtnMouseClicked(evt);
            }
        });
        registrationRegisterbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationRegisterbtnActionPerformed(evt);
            }
        });
        jPanel2.add(registrationRegisterbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 112, 40));

        jLabel3.setBackground(new java.awt.Color(51, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 94, -1));

        registerResetBtn.setBackground(new java.awt.Color(0, 153, 255));
        registerResetBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        registerResetBtn.setForeground(new java.awt.Color(255, 255, 255));
        registerResetBtn.setText("Reset");
        registerResetBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        registerResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerResetBtnActionPerformed(evt);
            }
        });
        jPanel2.add(registerResetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 78, 32));

        registerBackbtn.setBackground(new java.awt.Color(0, 153, 255));
        registerBackbtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        registerBackbtn.setForeground(new java.awt.Color(255, 255, 255));
        registerBackbtn.setText("Ke Login");
        registerBackbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        registerBackbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerBackbtnMouseClicked(evt);
            }
        });
        registerBackbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBackbtnActionPerformed(evt);
            }
        });
        jPanel2.add(registerBackbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 540, 111, 40));

        jLabel5.setBackground(new java.awt.Color(51, 0, 0));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 94, 21));

        jCheckBoxShowPass.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxShowPass.setText("Show Password");
        jCheckBoxShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxShowPassActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxShowPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, -1, 21));

        jLabel6.setBackground(new java.awt.Color(51, 0, 0));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Confirm Password:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 137, -1));

        rolebox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        rolebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Role Anda", "Staf", "Kasir" }));
        rolebox.setBorder(null);
        jPanel2.add(rolebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 260, 40));

        fNamefield.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fNamefield.setBorder(null);
        fNamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNamefieldActionPerformed(evt);
            }
        });
        jPanel2.add(fNamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 260, 40));

        lNamefield.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lNamefield.setBorder(null);
        jPanel2.add(lNamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 260, 38));

        emailField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        emailField.setBorder(null);
        jPanel2.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 260, 40));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setBackground(new java.awt.Color(204, 255, 204));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 255));
        jLabel7.setText("DAFTAR/REGISTRATION");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 590));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Untitled design(23).png"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 520, 590));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 570, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrationRegisterbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrationRegisterbtnMouseClicked

    }//GEN-LAST:event_registrationRegisterbtnMouseClicked

    private void registrationRegisterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationRegisterbtnActionPerformed
        String role = this.rolebox.getSelectedItem().toString();
        String fName = this.fNamefield.getText();
        String lName = this.lNamefield.getText();
        String email = this.emailField.getText();
        String pword = this.passwordfield.getText();

        if (this.confirmpassfield.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Confirm your Password!", "Alert", JOptionPane.ERROR_MESSAGE);
        } else if (this.passwordfield.getText() == null ? this.confirmpassfield.getText() != null : !this.passwordfield.getText().equals(this.confirmpassfield.getText())) {
            JOptionPane.showMessageDialog(null, "Password doesn't Match!", "Alert", JOptionPane.ERROR_MESSAGE);
            this.confirmpassfield.setText("");
        } else {

            try {
                Class.forName("com.mysql.jdbc.Driver");// The DriverManager class is the component of JDBC API and also a member of the java.sql package. The DriverManager class acts as an interface between users and drivers. It keeps track of the drivers that are available and handles establishing a connection between a database and the appropriate driver.

                try (Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/management_system", "root", "")) {

                    Statement stmt = con.createStatement();

                    String query1 = "INSERT INTO `users`(`FirstName`, LastName, `Email`, `Password`, `Role`, `Status`) VALUES"
                    + "('" + fName + "','" + lName + "','"  + email + "','" + pword + "','" + role + "', 'InActive')";

                    stmt.executeUpdate(query1);

                    JOptionPane.showMessageDialog(this, "Registered Successfully");
                }

            } catch (ClassNotFoundException | SQLException e) {

                System.out.println(e.getMessage());

            }
            this.rolebox.setSelectedIndex(0);
            this.fNamefield.setText(null);
            this.lNamefield.setText(null);
            this.emailField.setText(null);
            this.passwordfield.setText(null);
            this.confirmpassfield.setText(null);

        }
    }//GEN-LAST:event_registrationRegisterbtnActionPerformed

    private void registerResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerResetBtnActionPerformed
        if (evt.getSource() == registerResetBtn) {
            fNamefield.setText("");
            lNamefield.setText("");
            emailField.setText("");
            emailField.setText("");
            confirmpassfield.setText("");
            passwordfield.setText("");
            this.rolebox.setSelectedIndex(0);
        }
    }//GEN-LAST:event_registerResetBtnActionPerformed

    private void registerBackbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBackbtnMouseClicked
        new LoginPage().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_registerBackbtnMouseClicked

    private void registerBackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBackbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerBackbtnActionPerformed

    private void jCheckBoxShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxShowPassActionPerformed
        if (evt.getSource() == jCheckBoxShowPass) {
            if (jCheckBoxShowPass.isSelected()) {
                passwordfield.setEchoChar((char) 0);
                confirmpassfield.setEchoChar((char) 0);

            } else {
                passwordfield.setEchoChar('*');
                confirmpassfield.setEchoChar('*');
            }
        }
    }//GEN-LAST:event_jCheckBoxShowPassActionPerformed

    private void fNamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNamefieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmpassfield;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField fNamefield;
    private javax.swing.JCheckBox jCheckBoxShowPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField lNamefield;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JButton registerBackbtn;
    private javax.swing.JButton registerResetBtn;
    private javax.swing.JButton registrationRegisterbtn;
    private javax.swing.JComboBox<String> rolebox;
    // End of variables declaration//GEN-END:variables
}
